-- Generated by DSL
-- 2024-12-27 14:49:49

local UE = RE
local UF = FC

local ack_s = {
    tid = 1,
    ds = 1.5,
    df = "测试",
    type = EM.Test,
    ss = {
        EM.Test,
        {
            1
        }
    },
    XX1 = function(ctx, o)
        local a = UE.AA(ctx, 0, 100)
        if not a < 50 then
            return false
        elseif a > 50 and a < 70 then
            return true
        elseif a > 6 then
            return ture
        else
            return false
        end
    end,
    XX2 = function(ctx, o)
        do
            local i = 0
            while i < 10 do
                UF.DoSomething1(ctx)
                UF.XX(ctx)
                UF.DoSomething2(ctx)
                i = i + 1
            end
        end
        for k, v in pairs(units) do
            UF.DoSomething(ctx)
            UF.XX(ctx)
        end
        while UE.Do(ctx, 0, 100) > 50 do
            UF.Do1(ctx)
            UF.XX(ctx)
            UF.Do1(ctx)
        end
    end,
    XX3 = function(ctx, t)
        if UE.AA(ctx, t, 0.5) then
            UF.BB(ctx, t, 32, 3)
        else
            UF.BV(ctx, t, 2, 3)
        end
        return true
    end,
    XX4 = function(ctx, t)
        if (UE.PP(ctx, t, 0.1) or UE.XXX(ctx, t, 4)) and UE.YYY(ctx, t, 0.1) then
            UF.OP(ctx, t, 1, 3)
        else
            UF.CD(ctx, t, 1, 3)
        end
        if a > 5 then
            return fasle
        end
    end,
    XX5 = function(ctx, a)
        if UE.XM(ctx, t, 0.1) then
            UF.SM(ctx, t, 1, 3)
        end
        UF.OI(ctx, t, 30)
        UF.AddState(ctx, t, 1, 2)
        local x = UF.UY(ctx, t, "x_")
        UF.TY(ctx, t, x * 0.3)
        UF.RE(ctx, t, 1, 2)
    end
}

local sname = {
    tid = 1,
    map = {
        id = 2,
        ss = 1,
        [1] = 5,
        4,
        6,
        8,
        6.7,
        ["tsad"] = 45,
        {
            v = 5
        },
        {
            4,
            6,
            7
        },
        [6] = {
            4,
            6,
            7
        },
        testfun = function(p1)
        end
    },
    tt = 1,
    xs = 1,
    cc = 0,
    YY1 = function(ctx, unit)
    end,
    YY2 = function(ctx, unit)
    end
}

return {
    skills = {
        [1] = ack_s,
    },
    states = {
        [1] = sname,
    }
}