-- Generated by DSL
-- 2024-12-31 10:47:44

local UE = RE
local UF = FC

local s1 = {
    sd = {
        EM.Test,
        {
            1
        }
    },
    tid = 1,
    name = "测试",
    ss = {
        [1] = {
            1,
            2,
            3
        },
        [5] = {
            1,
            5,
            4
        }
    }
}
