-- Generated by DSL
-- 2024-12-27 16:37:25

local UE = RE
local UF = FC

for i = 10, 1, -2 do
    print(i)
end
print("----------------\\n")
for i = 1, 10 do
    print(i)
end
print("----------------\\n")
for i = 0, 10, 2 do
    print(i)
end
print("----------------\\n")
do
    local i = 10
    while i > 1 do
        print(i)
        i = i - 2
    end
end
for k, v in pairs(units) do
end
while UE.Do(ctx, 0, 100) > 50 do
end
